# Run all services databases for local development
version: '3.8'

services:
  db:
    container_name: db
    image: postgres:14-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=bigorna@DB
    ports:
      - '5432:5432'
  minio:
    container_name: minio
    image: minio/minio:latest
    volumes:
      - miniodata:/data
    environment:
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    ports:
      - '9000:9000'
      - '9001:9001'
    command: server --console-address ":9001" /data

volumes:
  dbdata:
  miniodata:
